### ISSUE TITLE
Viewport goes blank on master

### ISSUE THREAD

**Issue by Tyriar** [sourcelair/xterm.js#385]
Lots of output seems to be the repro, but it's inconsistent. I hit it when running vscode's tests.

![image](https://cloud.githubusercontent.com/assets/2193314/20701955/79a92310-b5ca-11e6-9474-ca847272bab8.png)

```
index.js:22 [uncaught exception]: TypeError: Cannot read property '0' of undefinedonError @ index.js:22
index.js:25 TypeError: Cannot read property '0' of undefined
    at Terminal.refresh (xterm.js:1516)
    at xterm.js:1473onError @ index.js:25
xterm.js:1516 Uncaught TypeError: Cannot read property '0' of undefined
index.js:22 [uncaught exception]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.onError @ index.js:22
index.js:25 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at Terminal.refresh (/usr/share/code-insiders/resources/app/node_modules/xterm/dist/xterm.js:1492:26)
    at /usr/share/code-insiders/resources/app/node_modules/xterm/dist/xterm.js:1473:22onError @ index.js:25
xterm.js:1492 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
index.js:22 [uncaught exception]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.onError @ index.js:22
index.js:25 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at Terminal.refresh (/usr/share/code-insiders/resources/app/node_modules/xterm/dist/xterm.js:1492:26)
    at /usr/share/code-insiders/resources/app/node_modules/xterm/dist/xterm.js:1473:22onError @ index.js:25
xterm.js:1492 Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
index.js:22 [uncaught exception]: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.onError @ index.js:22
index.js:25 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at Terminal.refresh (/usr/share/code-insiders/resources/app/node_modules/xterm/dist/xterm.js:1492:26)
    at /usr/share/code-insiders/resources/app/node_modules/xterm/dist/xterm.js:1473:22
```

**Comment by Tyriar** [comment]
First error is on this line in `refresh` (the X icon):

![image](https://cloud.githubusercontent.com/assets/2193314/20701975/9c9fe80e-b5ca-11e6-8289-fdccafe92dce.png)

**Comment by Tyriar** [comment]
Better repro:

1. Start command with lots of output
2. Scroll up

**Comment by Tyriar** [comment]
Debugging doesn't make much sense row or line sometimes eval as `undefined`, when stopped in a debugger though they look like they should be fine.

![image](https://cloud.githubusercontent.com/assets/2193314/20703145/83468e80-b5cf-11e6-9cc8-5e70fde2a142.png)

**Comment by Tyriar** [comment]
I haven't seen this for a while, removing important.

**Comment by Tyriar** [comment]
This may have been fixed by https://github.com/Tyriar/xterm.js/commit/a9e1ed5a72f23a53d681eaa8a939a88e24e26cbc

**Comment by BenHall** [comment]
I pushed live Tyriar@a9e1ed5 but I'm still seeing this behaviour.

I see the errors "Cannot set property '0' of undefined" occurring, but they no longer clear the display and visually everything looks to be OK. The problem seems to be when inside Vim and can result in Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
 

```
Uncaught TypeError: Cannot set property '0' of undefined
    at Terminal.write (CompositionHelper.ts:232)
    at Socket.<anonymous> (terminal-application.js:18)
    at Socket.Emitter.emit (socket.io.js:35)
    at Socket.onevent (socket.io.js:16)
    at Socket.onpacket (socket.io.js:15)
    at Manager.<anonymous> (socket.io.js:29)

CompositionHelper.ts:173 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Terminal.refresh (https://katacoda.com/javascripts/term.js:144:185)
    at https://katacoda.com/javascripts/term.js:141:33
Terminal.refresh @ CompositionHelper.ts:173
(anonymous) @ CompositionHelper.ts:168
setTimeout (async)
Terminal.refresh @ CompositionHelper.ts:168
Terminal.write @ EventEmitter.js:39

```

**Comment by parisk** [comment]
Seems like a9e1ed5 is irrelevant to the issue as it protects from using a negative index, while the problem here is that the "array" is `undefined`.

Taking a look.

**Comment by parisk** [comment]
@BenHall do you have any steps to reproduce available?

**Comment by Tyriar** [comment]
This should no longer happen due to checks added in https://github.com/sourcelair/xterm.js/issues/473
