### ISSUE TITLE
Am I the Only One Having This Issue?

### ISSUE THREAD

**Issue by snuggs** [sourcelair/xterm.js#501]
![capture d ecran 2017-01-21 a 08 27 56](https://cloud.githubusercontent.com/assets/38223/22174746/9b40a684-dfb3-11e6-8ee6-3d767d3d0e57.png)

## Details
- Browser and browser version: 
- OS version: 
- xterm.js version: 

### Steps to reproduce

1. 
2.

**Comment by vincentwoo** [comment]
OS version would be super helpful here, as this looks like an issue with `node-pty` which has a native code component.

**Comment by Tyriar** [comment]
Can you try reinstall deps?

```
rm -rf node_modules
npm i
```

**Comment by bitboxx** [comment]
I am not OP, but I have the same problem as him. From the screenshot I can tell he is running OS X Yosemite (Darwin 14.5.0). I am running the latest Arch Linux. 

Deleting node_modules and reinstalling everything did solve the problem.

The problem starts with during `npm install`. It does not complete the process and exits with error code. @vincentwoo is right, it has something to do with `node-pty`.

I'm going to Google this a bit further, but ideas on how to solve this are welcome.

Excerpt from npm-debug log:
```
52107 silly install node-pty@0.4.1
52108 info lifecycle node-pty@0.4.1~install: node-pty@0.4.1
52109 verbose lifecycle node-pty@0.4.1~install: unsafe-perm in lifecycle false
52110 verbose lifecycle node-pty@0.4.1~install: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/xterm.js/node_modules/node-pty/node_modules/.bin:/opt/xterm.js/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
52111 verbose lifecycle node-pty@0.4.1~install: CWD: /opt/xterm.js/node_modules/node-pty
52112 silly lifecycle node-pty@0.4.1~install: Args: [ '-c', 'node scripts/install.js' ]
52113 verbose stack Error: spawn ENOMEM
52113 verbose stack     at exports._errnoException (util.js:1023:11)
52113 verbose stack     at ChildProcess.spawn (internal/child_process.js:313:11)
52113 verbose stack     at exports.spawn (child_process.js:387:9)
52113 verbose stack     at spawn (/usr/lib/node_modules/npm/lib/utils/spawn.js:21:13)
52113 verbose stack     at runCmd_ (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:271:14)
52113 verbose stack     at /usr/lib/node_modules/npm/lib/utils/lifecycle.js:235:7
52113 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:67:7)
52113 verbose stack     at process._tickCallback (internal/process/next_tick.js:98:9)
52114 verbose cwd /opt/xterm.js
52115 error Linux 4.9.8-1-ARCH
52116 error argv "/usr/bin/node" "/usr/bin/npm" "install"
52117 error node v7.5.0
52118 error npm  v4.1.2
52119 error code ENOMEM
52120 error errno ENOMEM
```

Trying to start it will return this...
```
root@arch-5fd7 /opt/xterm.js (git)-[master] # npm start                                                                                              :(

> xterm@2.3.1 prestart /opt/xterm.js
> npm run build


> xterm@2.3.1 build /opt/xterm.js
> gulp build

[18:36:50] Using gulpfile /opt/xterm.js/gulpfile.js
[18:36:50] Starting 'tsc'...
[18:36:54] Finished 'tsc' after 4.32 s
[18:36:54] Starting 'browserify'...
[18:36:58] Finished 'browserify' after 3.17 s
[18:36:58] Starting 'sorcery'...
[18:37:01] Finished 'sorcery' after 3.6 s
[18:37:02] Starting 'build'...
[18:37:02] Finished 'build' after 581 ms

> xterm@2.3.1 start /opt/xterm.js
> node demo/app

Cannot find module '../build/Release/pty.node'
module.js:472
    throw err;
    ^

Error: Cannot find module '../bin/linux/x64.m51.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/xterm.js/node_modules/node-pty/lib/pty.js:18:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Linux 4.9.8-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! xterm@2.3.1 start: `node demo/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xterm@2.3.1 start script 'node demo/app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xterm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node demo/app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xterm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xterm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/xterm.js/npm-debug.log
npm start  10.16s user 2.08s system 68% cpu 17.821 total
```

**Comment by Tyriar** [comment]
Note that if you change the version of node that you built with, you will need to delete `node_modules/node-pty` and run `npm install` again, that's likely the root cause of the OP.

@bitboxx the error you're getting in npm-debug.log is different but it's an `ENOMEM` error (out of memory).

**Comment by bitboxx** [comment]
@Tyriar Thanks. The VM I was running had 512MB RAM, I doubled it and it solved the problem. Sigh... 1GB just to be able to install packages.

**Comment by Tyriar** [comment]
@bitboxx that's definitely the issue then :smile: node is not the most memory efficient thing sometimes.

**Comment by snuggs** [comment]
Thanks all for this update!
\
