### ISSUE TITLE
xterm.js version 2.3.0-2.3.1 gulpfile error

### ISSUE THREAD

**Issue by l3m0n** [sourcelair/xterm.js#536]
xterm.js version: 2.3.0 \ 2.3.1
```
npm install
npm start
```

but i run `npm start`,it have a error
when i use xterm.js version: 2.2.3,i'm successed run.

```
/usr/src/app/xterm.js-2.3.0/gulpfile.js:13
let buildDir = process.env.BUILD_DIR || 'build';
    ^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/src/app/xterm.js-2.3.0/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/src/app/xterm.js-2.3.0/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/src/app/xterm.js-2.3.0/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/src/app/xterm.js-2.3.0/node_modules/gulp/node_modules/liftoff/index.js:190:9)
```

## Details
- OS version: ubuntu 14.04
- xterm.js version: 2.3.0 \ 2.3.1

**Comment by Tyriar** [comment]
What version of node are you on?

**Comment by l3m0n** [comment]
v0.10.46

**Comment by Tyriar** [comment]
You will need to update your node, that so old it doesn't support `let` is the issue.
